final topic = [
  // BOOK 1
  // 예비편
  "한글 익히기 Ⅰ",
  "한글 익히기 Ⅱ",
  "교실 한국어",
  "안녕하세요",
  "주말 잘 보내세요",
  // 기본 생활
  "저는 투안입니다 ",
  "여기가 사무실이에요",
  "12시 30분에 점심을 먹어요",
  "가족이 몇 명이에요?",
  "어제 도서관에서 한국어를 공부했어요",
  "사과 다섯 개 주세요",
  "병원 옆에 약국이 있어요",
  "시청 앞에서 일곱 시에 만나요",
  "저는 비빔밥을 먹을래요",
  "날씨가 맑아서 기분이 좋아요",
  // 일상 및 여가 생활
  "시간이 있을 때 주로 테니스를 치러 가요",
  "휴가 때 제주도에 다녀올 거예요",
  "버스나 지하철을 타고 가요",
  "거기 한국가구지요?",
  "저는 설거지를 할게요",
  "상 차리는 것을 도와줄까요?",
  "무단횡단을 하면 안 돼요",
  "어른께는 두 손으로 물건을 드려야 돼요",
  "한국 영화를 보면서 공부해요",
  "일요일마다 교회에 가요",
  // 공공기관
  "밥을 먹은 후에 이 약을 드세요",
  "어디가 아프십니까?",
  "통장을 만들려고 왔어요",
  "필리핀으로 엽서를 보내고 싶은데요",
  "거기에서 태권도를 배울 수 있어요?",

  // BOOK 2
  // 한국에 대한 이해
  "우리 고향은 서울보다 공기가 맑아요",
  "복날에는 삼계탕을 먹어요",
  "송편을 만드는 체험도 할 수 있어요",
  " 아기 옷을 선물하는 게 어때요?",
  "한국 드라마가 재미있잖아요",
  // 직장 문화
  "단정한 모습이 좋아 보여요",
  "출입문을 꼭 닫읍시다",
  "일할 맛이 나요",
  "오늘 회식을 하자고 해요",
  "불쾌감을 느꼈다면 그건 성희롱이에요",
  // 직장 생활
  "드라이버로 해 보세요",
  "이 기계 어떻게 작동하는지 알아요? ",
  "철근을 옮겨 놓으세요",
  "페인트 작업을 했거든요",
  "호미를 챙겼는데요",
  "더 신경 쓰도록 하자",
  "재고를 파악하는 것이 중요해요",
  "다치지 않도록 조심하세요",
  "안전화를 안 신으면 다칠 수 있어요",
  "열심히 해 준 덕분이에요",
  // 법령 및 제도
  "한국에 가서 일하고 싶은데요",
  "근로 조건이 좋은 편이에요",
  "외국인 등록을 하러 가요",
  "보험금을 신청하려고요",
  "급여 명세서를 확인해 보세요",
  "이번 여름 휴가 계획은 세웠어?",
  "사업장을 변경하고 싶은데",
  "체류 기간을 연장한 후에 꼭 신고해야 해",
  // 직장 생활 용어
  "산업 안전 Ⅰ",
  "산업 안전 Ⅱ",
];

final topicTrans = [
  // BOOK 1
  // 예비편
  "Master Hangeul, the Korean Alphabet I",
  "Master Hangeul, the Korean Alphabet II",
  "Korean Classroom Expressions",
  "Hello",
  "Have a great weekend",
  // 기본 생활
  "My name is Tuan",
  "This is the office",
  "I have lunch at 12:30pm",
  "How many family members do you have?",
  "I studied Korean at the library yesterday",
  "Please give me five apples",
  "There is a pharmacy next to the hospital",
  "Let's meet in front of the CIty Hall at 7 o'clock",
  "I would like to have Bibimbap",
  "I feel good that the weather is clear and sunny",
  // 일상 및 여가 생활
  "I usually go play tennis when I have time",
  "I will go visit Jeju-do the break",
  "I go bus or by subway",
  "This is Hankook Furniture, isn't it?",
  "I will wash the dishes",
  "Would you like some help setting the table",
  "Please do not jaywalk",
  "Please use both hands when giving things to your elders",
  "I watch korean movies to study the korean language",
  "I go to church every Sunday",
  // 공공기관
  "Please take this medication after a meal",
  "Where are you hurting?",
  "I came to open a bank account",
  "I would to like to send postcard to Philippine",
  "Can I learn Taekwondo there?",
  // BOOK 2
  // 한국에 대한 이해
  "It's much fresher in my hometown than it is in Seoul",
  "We eat Samgyetang on the hottest day of the year in summer",
  "You can try making Songpyeon, half-mmon shaped rice cake",
  "How about giving baby clothes as a gift?",
  "As you already know, Korean dramas are fun",
  // 직장 문화
  "It's good that you look neat and tidy",
  "keep the entrance closed",
  "I feel like working here",
  "I was told that we would have comapny dinner today",
  "If she feels uncomfortable, then, that's sexual harresment",
  // 직장 생활
  "Try a screwdriver",
  "Do you know how to operate thid machine",
  "Please move rebar",
  "it's because I painted",
  "I have had my hoe ready",
  "Let's keep an eye open on them",
  "It's is important to keep track of the stock",
  "Please make sure that you don't get injured",
  "If you don't wear safety shoes, you may get injured",
  "You should take credit for this",
  // 법령 및 제도
  "I would like to work in Korea",
  "I've been offered pretty decent working confitions",
  "I'm on the way to do alien registration",
  "I plan to file an insurance claim",
  "Please check your pay stub",
  "Have you planned your summer vacation?",
  "I would like to change my work location",
  "You have to report to the office after extending your stay",
  // 직장 생활 용어
  "Industrial Safety I",
  "Industrial Safety II",
];

final pdfLocationList = [
  'pdfAssets/1.pdf',
  'pdfAssets/2.pdf',
  'pdfAssets/3.pdf',
  'pdfAssets/4.pdf',
  'pdfAssets/5.pdf',
  'pdfAssets/6.pdf',
  'pdfAssets/7.pdf',
  'pdfAssets/8.pdf',
  'pdfAssets/9.pdf',
  'pdfAssets/10.pdf',
  'pdfAssets/11.pdf',
  'pdfAssets/12.pdf',
  'pdfAssets/13.pdf',
  'pdfAssets/14.pdf',
  'pdfAssets/15.pdf',
  'pdfAssets/16.pdf',
  'pdfAssets/17.pdf',
  'pdfAssets/18.pdf',
  'pdfAssets/19.pdf',
  'pdfAssets/20.pdf',
  'pdfAssets/21.pdf',
  'pdfAssets/22.pdf',
  'pdfAssets/23.pdf',
  'pdfAssets/24.pdf',
  'pdfAssets/25.pdf',
  'pdfAssets/26.pdf',
  'pdfAssets/27.pdf',
  'pdfAssets/28.pdf',
  'pdfAssets/29.pdf',
  'pdfAssets/30.pdf',
  'pdfAssets/31.pdf',
  'pdfAssets/32.pdf',
  'pdfAssets/33.pdf',
  'pdfAssets/34.pdf',
  'pdfAssets/35.pdf',
  'pdfAssets/36.pdf',
  'pdfAssets/37.pdf',
  'pdfAssets/38.pdf',
  'pdfAssets/39.pdf',
  'pdfAssets/40.pdf',
  'pdfAssets/41.pdf',
  'pdfAssets/42.pdf',
  'pdfAssets/43.pdf',
  'pdfAssets/44.pdf',
  'pdfAssets/45.pdf',
  'pdfAssets/46.pdf',
  'pdfAssets/47.pdf',
  'pdfAssets/48.pdf',
  'pdfAssets/49.pdf',
  'pdfAssets/50.pdf',
  'pdfAssets/51.pdf',
  'pdfAssets/52.pdf',
  'pdfAssets/53.pdf',
  'pdfAssets/54.pdf',
  'pdfAssets/55.pdf',
  'pdfAssets/56.pdf',
  'pdfAssets/57.pdf',
  'pdfAssets/58.pdf',
  'pdfAssets/59.pdf',
  'pdfAssets/60.pdf',
];
